let numbers = [1, 2, 3, 4, 5];
let strings = ['hi', 'how are you', 'goodbye'];
console.log(numbers);
console.log(strings);
console.log(numbers);
console.log(strings);
console.log(numbers);
console.log(strings);
console.log(numbers);
console.log(strings);